clc
clear all
close all

Template=readtable("DBPG.csv");
OldDB=Template(:,1:6);

l=height(OldDB);

PLC1_AI_LT_STRAMAZZO=cell(l,1)
PLC1_AI_LT_STRAMAZZO(:)={'ND'}

x__TimeStamp=OldDB.x__TimeStamp;
PLC1_AI_PT_LINEA=OldDB.PLC1_AI_PT_LINEA;
PLC1_AI_PT_TURBINA=OldDB.PLC1_AI_PT_TURBINA;
PLC1_AI_POT_ATTIVA=OldDB.PLC1_AI_POT_ATTIVA;
PLC1_AI_FT_PORT_IST=OldDB.PLC1_AI_FT_PORT_IST;
PLC1_AI_COSPHI=OldDB.PLC1_AI_COSPHI;

newTab=table(x__TimeStamp,PLC1_AI_PT_LINEA,PLC1_AI_PT_TURBINA,PLC1_AI_POT_ATTIVA,PLC1_AI_FT_PORT_IST,PLC1_AI_COSPHI,PLC1_AI_LT_STRAMAZZO);

%newTab = append(OldDB, PLC1_AI_LT_STRAMAZZO);
