function HTMLTable=createTable(TipoImpianto,TipoTempo,Tempo,VariabileGeneratrice,Potenza,PR,percConc,PlantName)

if ismissing(PR)
    PR="NAN";
end

if TipoImpianto=="PV"

    if TipoTempo=="Now"
        Head=["Ultimo TimeStamp","Irraggiamento","Potenza","PR"];
        udm=["W/m<sup>2</sup>","kW"];
        TabTitle="Prestazioni attuali";
    else
        Head=["Data","Energia Irradiata","Energia Prodotta","PR"];
        udm=["kWh/m<sup>2</sup>","kWh"];
        TabTitle="Prestazioni odierne";

    end

        HTMLTable="<center><table style="+char(34)+"border:2px solid black; border-collapse: collapse;"+char(34)+" width="+char(34)+"1000"+char(34)+">"+...
        "<caption style="+char(34)+"border: 2px solid; text-align:center; border-collapse: collapse"+char(34)+">"+...
        "<b>"+TabTitle+"</b>"+...
        "</caption>"+...
        "<thead>"+...
        "<tr>" + ...
        "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(1)+"</th>" + ...
        "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(2)+"</th>" + ...
        "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(3)+"</th>" + ...
        "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(4)+"</th></tr>"+...
        "</thead>"+...
        "<body>"+...
        "<tr>" + ...
        "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Tempo+"</td>" + ...
        "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+VariabileGeneratrice+" "+udm(1)+"</td>" + ...
        "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Potenza+" "+udm(2)+"</td>" + ...
        "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+PR+" %</td></tr>"+...
        "</body>"+...
        "</table></center>";





else

    %     VariabileGeneratrice=round(double(VariabileGeneratrice),1);
    if TipoTempo=="Now"
        Head=["Ultimo TimeStamp","Portata","Potenza","&eta;"];
        
        udm=["l/s","kW"];
        if PlantName == "TF"
                udm=["m<sup>3</sup>/s","kW"];
        end
        TabTitle="Prestazioni attuali";

        HTMLTable="<center><table style="+char(34)+"border:2px solid black; border-collapse: collapse;"+char(34)+" width="+char(34)+"1000"+char(34)+">"+...
            "<caption style="+char(34)+"border: 2px solid; text-align:center; border-collapse: collapse"+char(34)+">"+...
            "<b>"+TabTitle+"</b>"+...
            "</caption>"+...
            "<thead>"+...
            "<tr>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(1)+"</th>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(2)+"</th>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(3)+"</th>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(4)+"</th></tr>"+...
            "</thead>"+...
            "<body>"+...
            "<tr>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Tempo+"</td>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+VariabileGeneratrice+" "+udm(1)+"</td>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Potenza+" "+udm(2)+"</td>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+PR+" %</td></tr>"+...
            "</body>"+...
            "</table></center>";

    else

%         Vol=VariabileGeneratrice;
        Head=["Data","Volume derivato (esaurimento giornaliero)","Energia Prodotta","&eta;"];

        udm=["m<sup>3</sup>","kWh"];
        TabTitle="Prestazioni odierne";

        HTMLTable="<center><table style="+char(34)+"border:2px solid black; border-collapse: collapse;"+char(34)+" width="+char(34)+"1000"+char(34)+">"+...
            "<caption style="+char(34)+"border: 2px solid; text-align:center; border-collapse: collapse"+char(34)+">"+...
            "<b>"+TabTitle+"</b>"+...
            "</caption>"+...
            "<thead>"+...
            "<tr >" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(1)+"</th>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(2)+"</th>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(3)+"</th>" + ...
            "<th style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Head(4)+"</th></tr>"+...
            "</thead>"+...
            "<body>"+...
            "<tr>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Tempo+"</td>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+VariabileGeneratrice+" "+udm(1)+" ("+percConc+" %)</td>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+Potenza+" "+udm(2)+"</td>" + ...
            "<td style="+char(34)+"border: 1px solid; text-align:center; border-collapse: collapse"+char(34)+">"+PR+" %</td></tr>"+...
            "</body>"+...
            "</table></center>";

    end

end






end